name: 'discursus_mvp'
version: '0.1.0'
config-version: 2

profile: 'discursus_mvp'

model-paths: ["models"]
seed-paths: ["data"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  discursus_mvp:
    +schema: sources
    gdelt_articles:
      +column_types:
        article_date: varchar

models:
  discursus_mvp:
    +materialized: table