[tool.poetry]
name = "mvp"
version = "0.1.0"
description = ""
authors = ["Olivier Dupuis <odupuis@lantrns.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
dbt-core = "^1.6.1"
dbt-duckdb = "^1.6.0"
dagster = "^1.4.10"
dagster-dbt = "^0.20.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
