name: 'mvp_source_prep'
version: '0.1.0'
config-version: 2

profile: 'mvp_source_prep'

model-paths: ["models"]
seed-paths: ["data"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  mvp_source_prep:
    +schema: sources
    gdelt_articles:
      +column_types:
        article_date: varchar

models:
  mvp_source_prep:
    +materialized: table
    staging:
      +schema: staging
    integration:
      +schema: integration