account: 
  env: SNOWFLAKE_ACCOUNT
user: 
  env: SNOWFLAKE_USER
password: 
  env: SNOWFLAKE_PASSWORD
role:
  env: SNOWFLAKE_ROLE
warehouse: 
  env: SNOWFLAKE_LOAD_WAREHOUSE
database: 
  env: SNOWFLAKE_LOAD_DATABASE
schema: 
  env: SNOWFLAKE_LOAD_SCHEMA