name: 'discursus_stage_sources'
version: '0.1.0'
config-version: 2

profile: 'discursus_stage_sources'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  discursus_stage_sources:
    +materialized: table